language: python

services: docker

python:
  - "3.6"

install: pip install tox

script:
  - tox

deploy:

    # Deploy image to DockerHub
  - provider: script
    script: release/image_dockerhub.sh
    on:
      branch: master
