language: python

services: docker

python:
  - "3.6"

install: pip install tox

script:
  - tox

deploy:

    # Deploy to Docker
  - provider: script
    script: deploy/docker.sh
    on:
      branch: master
