version: '3'

services:

  postgres:
    image: postgres:9.6-alpine
    ports:
      - 5433:5433
    environment:
      - POSTGRES_PASSWORD=postgres
    command: -p 5433

  redis:
    image: redis:3-alpine
    ports:
      - 6379:6379
